### ISSUE TITLE
API MISUSE: <CBCentralManager: 0x600003305ae0> can only accept this command while in the powered on state

### ISSUE THREAD

**Issue by namrataroy11** [leonardocavagnis/iOSArduinoBLE_iOSApp#1]
I have downloaded your source code as is. However, after I have build it into my device, and when I press the Scan Button the following error arise.  API MISUSE: <CBCentralManager: 0x600003305ae0> can only accept this command while in the powered on state

**Comment by leonardocavagnis** [comment]
Look at this:
https://stackoverflow.com/questions/23338767/ios-core-bluetooth-getting-api-misuse-warning
And let me know if it works

**Comment by yunhaod** [comment]
I'm also experiencing the same issue. The stackoverflow discussion seems to direct the solution to calling 
        centralManagerDidUpdateState(central) 
prior to accepting commands. I have added this line of code to this function inside the CentralUseCase as shown below:
    func scan(for services: [CBUUID]) {
        guard central.isScanning == false else {
            return
        }
        centralManagerDidUpdateState(central)
        central.scanForPeripherals(withServices: services, options: [:])
The issue is still there and I'm not quite sure how to fix it. Any insight would be helpful

**Comment by leonardocavagnis** [comment]
Make sure your Bluetooth is turned on, and if the issue persists, try waiting a few seconds after launching the app before tapping the scan button. Let me know if this resolves the problem

**Comment by yunhaod** [comment]
ok I think the issue is turning on bluetooth in "signing and capabilities". Also adding "privacy-bluetooth peripheral usage description" and "privacy- bluetooth always usage description"  under project info might have solved that issue.

**Comment by leonardocavagnis** [comment]
@yunhaod great! 
could you attach some screenshots about solving this issue to be useful for others?
Thanks

**Comment by yunhaod** [comment]
<img width="742" alt="Screenshot 2024-01-14 at 6 37 37 PM" src="https://github.com/leonardocavagnis/iOSArduinoBLE_iOSApp/assets/117396171/79753878-3ddd-4433-9100-2578234a71f7">
<img width="677" alt="Screenshot 2024-01-14 at 6 38 15 PM" src="https://github.com/leonardocavagnis/iOSArduinoBLE_iOSApp/assets/117396171/458b59a4-f197-46f6-a4f9-dd0a13db4c46">
