### ISSUE TITLE
CB Central Manager not connecting to the peripheral

### ISSUE THREAD

**Issue by yunhaod** [leonardocavagnis/iOSArduinoBLE_iOSApp#3]
When I scan for the peripherals, it successfully picks up on the Arduino board and I was able click on it. However, the view model doesn't change. On the Arduino serial monitor, it indicates that it has been connected to a central.  While I was figuring out what happened, it looks like the CB Central Manager is stuck on trying to connect to peripheral. 

`Optional(<CBPeripheral: 0x60000079c000, identifier = 0D0A5BB7-9E87-1EF6-8C43-4F76D6F4ACCB, name = Arduino, mtu = 0, state = connecting>`

also when I retrieve the list of connected peripherals, the results came out to be empty. 

no matter how much I give, it has been stuck on trying to connect and won't switch to the connected view. Any idea on how to troubleshoot this?

**Comment by leonardocavagnis** [comment]
Hi @yunhaod 
What's your setup?
- Arduino model
- iPhone Model
- iOS version

**Comment by yunhaod** [comment]
- Arduino Nano 33 BLE
- Im running Xcode 15.2 and the iOS app is deployed on the "default" and being runned from my Mac instead of my phone 
- my Mac model is macOS Sonoma 14.2

**Comment by georgegmathew12** [comment]
@leonardocavagnis @yunhaod @DrAma999 
Has there been a fix for this? I'm having the exact same issue. 
Also using a Nano 33 BLE, iPhone XR, iOS 17.3.1, and Xcode 15.3.

**Comment by leonardocavagnis** [comment]
@georgegmathew12 @yunhaod 
Are you trying to run it on the simulator?
You should run the app on a real iPhone. BLE is not supported on iOS simulators.

**Comment by leonardocavagnis** [comment]
@georgegmathew12 @yunhaod 
Are you trying to run it on the simulator? or on real device?
BLE is not supported on iOS simulators.

**Comment by georgegmathew12** [comment]
I'm running it on my real iPhone XR with the specs as provided above.

**Comment by leonardocavagnis** [comment]
@georgegmathew12 
The original Arduino sketch is designed to work only with the Arduino Nano 33 BLE SENSE. If you want to run the sketch on the Arduino Nano 33 BLE, you have to modify the sketch by removing the temperature sensor reading. The temperature sensor is not present on the board. Remove that part and add a routine to generate random numbers to 'emulate' the sensor reading. I don’t know if this is the problem, but it's the first thing that comes to mind at the moment.

**Comment by georgegmathew12** [comment]
That worked! Thank you so much

**Comment by yunhaod** [comment]
This also fixed the issue for me when deployed on Mac! Thanks
