### ISSUE TITLE
'String UUID' does not represent a valid

### ISSUE THREAD

**Issue by FredWilhelmFR** [leonardocavagnis/iOSArduinoBLE_iOSApp#4]
Hello,

First thanks for the amazing job.
I am working on Xcode 15.3 (15E204a) and using the Simulator for iOS. Arduino is the original Nano 33 BLE.

First I had to add on plist the bluetooth services and privacies to avoid error on "XPC Service Connection". 
That works.

But now I have the following error : 'exception ''NSInternalInconsistencyException', reason: 'String UUID'
does not represent a valid" (cf screenshot).

Do I need to publish on the Store (and use my iPhone vs Simulator) to avoid the error ? (I didn't get my license yet).
Thanks for your feedback.
<img width="1804" alt="Screenshot xCode" src="https://github.com/leonardocavagnis/iOSArduinoBLE_iOSApp/assets/165156972/d4cc6664-a855-47a0-a301-4f9eec9ad08c">

**Comment by DrAma999** [comment]
Hello,
you should use a real device. Bluetooth LE is not supported on iOS simulators out of the box.
Best,
Andrea

**Comment by FredWilhelmFR** [comment]
Thanks Andrea. Same bug with the iPhone (vs Simulator).
iPhone screen remains white (Scan view is not pushed) and Xcode error is the following :
![Uploading Error.png…]()

**Comment by FredWilhelmFR** [comment]
Thanks for your help. The program build then run on my iPhone, the iPhone screen becomes white then Xcode debug window shows "Not handled" (cf screenshot), then the scan view is opening but I can't see the Arduino in the list (even after clicking on Start Scan). May be you have a clue of what I have done wrong...
![Uploading Capture d’écran 2024-03-28 à 10.17.54.png…]()

**Comment by FredWilhelmFR** [comment]
The team was super reactive and the program works perfectly ! Bravo !
